FROM openjdk:17-alpine
RUN addgroup -g 1001 -S appuser && adduser -S appuser -G appuser
USER appuser
COPY api-service/target/api-service-0.0.1-SNAPSHOT.jar /app/order-service.jar
CMD ["java","-jar","/app/order-service.jar"]