version: "3.8"

services:

  postgres:
    image: postgres:12-alpine
    container_name: db-postgres-product
    environment:
      POSTGRES_DB: db_product
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netms1

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: db-sqlserver-cart
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 1a.2b.3c.
      MSSQL_PID: Express
    ports:
      - 1433:1433
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1200M
        reservations:
          cpus: '0.25'
          memory: 500M
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - netms1

      # mysql:
      # image: mysql:8
      # container_name: db-mysql-security
      # restart: always
      # environment:
      # MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_DATABASE: db_segurity
      # ports:
      # - 3306:3306
      # networks:
      # - netms1

volumes:
  postgres_data:
    driver: local
  sql_data:
    driver: local

networks:
  netms1:
    name: net-ms1

