FROM openjdk:17-alpine
LABEL maintainer jlozano@uni.edu.pe
VOLUME /tmp
ADD api-service/target/*.jar app.jar
ENV JAVA_OPTS=""
EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]